### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by WillTester** [NerdSmith/MusicRecognizer#1]
Music is playing.  Program is running.   It listens for 30 seconds(set to speakers).  No results and the program stops working.  I have to close and reopen it to make another attempt which has the same results.

**Comment by NerdSmith** [comment]
Hello, can you give me more information about this?
What version of the program did you use? What version of Windows do you have? (And by the way, the program is only available on Windows)
Also, it will not be superfluous to check the contents of the app.log file and listen to the recorded sound excerpt.wav.
And there are times when the program cannot recognize the music.
