### ISSUE TITLE
Can t get it to work in Windows 11

### ISSUE THREAD

**Issue by mariofenech** [NerdSmith/MusicRecognizer#4]
Hi
Should this be working in windows 11?
I downloaded the precompiled latest version from releases and run the app from the exe but nothing is showing up..

log

INFO:root:devices have been found
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
DEBUG:urllib3.connectionpool:https://nameless-sierra-10297.herokuapp.com:443 "GET / HTTP/1.1" 503 506
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by NerdSmith** [comment]
> Hi Should this be working in windows 11? I downloaded the precompiled latest version from releases and run the app from the exe but nothing is showing up..
> 
> log
> 
> INFO:root:devices have been found DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 DEBUG:urllib3.connectionpool:https://nameless-sierra-10297.herokuapp.com:443 "GET / HTTP/1.1" 503 506 DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 ERROR:root:recognizer error ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Hello!
I'm so sorry this happened, but Heroku broke my api...
Source updates are online now
The release will be updated within an hour.

**Comment by mariofenech** [comment]
Thanks
